#!/usr/bin/env python3

import json
from pathlib import Path
from zk_contract import validate_bridge_zk_fixture_contract


ROOT_DIR = Path(__file__).resolve().parent.parent.parent
DATA_PATH = ROOT_DIR / "scripts" / "data" / "bridge_mint_raw.json"
OUTPUT_PATH = ROOT_DIR / "validators" / "tests" / "helpers" / "bridge_fixture.ak"


def read_json(path: Path) -> dict:
    return json.loads(path.read_text())


def ascii_hex(text: str) -> str:
    return text.encode().hex()

def validate_bridge_zk_fixture(data: dict) -> None:
    validate_bridge_zk_fixture_contract(data)


def render_bridge_fixture(data: dict) -> str:
    validate_bridge_zk_fixture(data)

    packed = data["packed_public_inputs"]
    tx_set_update_packed = data["tx_set_update_packed_public_inputs"]
    snapshot_proof = data["minting_merkle_proof"]
    tx_set_update_proof = data["tx_set_update_proof"]
    locking_tx_input_datum_hex = data.get("locking_tx_input_datum_hex", "")

    return f"""use ak_381/groth16.{{Proof}}
use bridge/common_types.{{LockingTxSourceOutputReference}}
use cardano/address.{{VerificationKey}}
use zk/verification.{{Single, ZKInputType}}

// Generated from scripts/data/bridge_mint_raw.json by
// scripts/python/sync_bridge_zk_fixture.py.
// Do not edit this file by hand; update the JSON fixture and regenerate.

pub const final_snapshot_root =
  #"{data["tx_snapshot_certificate_protocol_message_cardano_transactions_merkle_root_text"]}"

pub const final_sub_root =
  #"{data["locking_tx_merkle_proof_public_sub_root_hex"]}"

pub const final_locking_tx_hash =
  #"{data["locking_tx_hash_hex"]}"

// Legacy compatibility name: this is now the canonical Cardano tx hash.
pub const final_locking_tx_hash_hi = {packed["cardano_tx_hash_hi"]}
pub const final_locking_tx_hash_lo = {packed["cardano_tx_hash_lo"]}
pub const final_sub_root_hi = {packed["sub_root_hi"]}
pub const final_sub_root_lo = {packed["sub_root_lo"]}
pub const final_snapshot_root_hi = {packed["snapshot_root_hi"]}
pub const final_snapshot_root_lo = {packed["snapshot_root_lo"]}

pub const final_tx_set_update_root_in =
  #"{data["tx_set_update_old_merkle_root_hex"]}"

pub const final_tx_set_update_root_out =
  #"{data["new_merkle_root_hex"]}"

pub const actual_locking_tx_input_output_reference =
  LockingTxSourceOutputReference {{
    transaction_id: #"{ascii_hex(data["locking_tx_input_output_reference_tx_id_text"])}",
    output_index: {data["locking_tx_input_output_reference_output_index"]},
  }}

pub const actual_locking_tx_input_payment_credential =
  #"{ascii_hex(data["locking_tx_input_payment_credential_text"])}"

pub const actual_locking_tx_input_datum = #"{locking_tx_input_datum_hex}"

pub const actual_locking_tx_destination_address =
  VerificationKey(#"{data["actual_locking_tx_destination_payment_credential_hex"]}")

pub const actual_locking_tx_asset_amount = {data["bridge_asset_amount"]}
pub const actual_locking_tx_ada_amount = {data["locking_tx_ada_amount"]}

pub fn final_snapshot_membership_proof() -> Proof {{
  Proof {{
    piA: #"{snapshot_proof["piA"]}",
    piB: #"{snapshot_proof["piB"]}",
    piC: #"{snapshot_proof["piC"]}",
  }}
}}

pub fn final_tx_set_update_proof() -> Proof {{
  Proof {{
    piA: #"{tx_set_update_proof["piA"]}",
    piB: #"{tx_set_update_proof["piB"]}",
    piC: #"{tx_set_update_proof["piC"]}",
  }}
}}

pub fn final_snapshot_membership_public_inputs() -> List<ZKInputType> {{
  [
    Single(final_locking_tx_hash_hi),
    Single(final_locking_tx_hash_lo),
    Single(final_sub_root_hi),
    Single(final_sub_root_lo),
    Single(final_snapshot_root_hi),
    Single(final_snapshot_root_lo),
  ]
}}

pub fn final_tx_set_update_public_inputs() -> List<ZKInputType> {{
  [
    Single({tx_set_update_packed["tx_id_hi"]}),
    Single({tx_set_update_packed["tx_id_lo"]}),
    Single({tx_set_update_packed["mt_root_in"]}),
    Single({tx_set_update_packed["mt_root_out"]}),
  ]
}}
"""


def load_bridge_zk_fixture(path: Path = DATA_PATH) -> dict:
    data = read_json(path)
    validate_bridge_zk_fixture(data)
    return data


def write_bridge_fixture(output_path: Path = OUTPUT_PATH, data_path: Path = DATA_PATH) -> None:
    output_path.write_text(render_bridge_fixture(load_bridge_zk_fixture(data_path)))


def check_bridge_fixture(output_path: Path = OUTPUT_PATH, data_path: Path = DATA_PATH) -> None:
    rendered = render_bridge_fixture(load_bridge_zk_fixture(data_path))
    if not output_path.exists():
        raise SystemExit(f"missing generated file: {output_path}")
    if output_path.read_text() != rendered:
        raise SystemExit(
            f"{output_path} is out of date; run sync_bridge_zk_fixture.py to regenerate it"
        )
