#!/usr/bin/env python3

import json
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent.parent.parent
DATA_PATH = ROOT_DIR / "scripts" / "data" / "jubjub_schnorr_raw.json"
OUTPUT_PATH = ROOT_DIR / "validators" / "tests" / "helpers" / "jubjub_schnorr_fixture.ak"


def read_json(path: Path) -> dict:
    return json.loads(path.read_text())


def validate_jubjub_schnorr_fixture(data: dict) -> None:
    required_top_level = [
        "curve",
        "protocol",
        "public_inputs",
        "verified",
        "packed_public_inputs",
        "digest_hi",
        "digest_low",
        "message_base",
        "verification_key_u",
        "verification_key_v",
        "signature_response",
        "signature_challenge",
        "jubjub_schnorr_proof",
    ]
    for key in required_top_level:
        if key not in data:
            raise SystemExit(f"missing required field in jubjub_schnorr_raw.json: {key}")

    if data["curve"] != "bls12381":
        raise SystemExit(f"unexpected curve: {data['curve']}")
    if data["protocol"] != "groth16":
        raise SystemExit(f"unexpected protocol: {data['protocol']}")
    if data["public_inputs"] != 6:
        raise SystemExit(f"expected 6 public inputs, got {data['public_inputs']}")
    if data["verified"] is not True:
        raise SystemExit("expected verified=true in jubjub_schnorr_raw.json")

    packed = data["packed_public_inputs"]
    for key in [
        "digest_hi",
        "digest_low",
        "verification_key_u",
        "verification_key_v",
        "signature_response",
        "signature_challenge",
    ]:
        if str(packed[key]) != str(data[key]):
            raise SystemExit(
                f"packed_public_inputs.{key} does not match top-level {key}: "
                f"{packed[key]} != {data[key]}"
            )

    proof = data["jubjub_schnorr_proof"]
    for key in ["piA", "piB", "piC"]:
        value = proof.get(key, "")
        if not isinstance(value, str) or not value:
            raise SystemExit(f"missing proof field: {key}")


def render_jubjub_schnorr_fixture(data: dict) -> str:
    validate_jubjub_schnorr_fixture(data)
    proof = data["jubjub_schnorr_proof"]
    response = int(data["signature_response"])
    challenge = int(data["signature_challenge"])
    schnorr_signature_hex = (
        response.to_bytes(32, "little").hex()
        + challenge.to_bytes(32, "little").hex()
    )
    schnorr_signature_ascii_hex = schnorr_signature_hex.encode().hex()

    return f"""use aiken/primitive/bytearray
use aiken/primitive/string
use ak_381/groth16.{{Proof}}
use zk/verification.{{Single, ZKInputType}}

// Generated from scripts/data/jubjub_schnorr_raw.json by
// scripts/python/jubjub_schnorr_fixture.py.
// Do not edit this file by hand; update the JSON fixture and regenerate.

pub const final_message_base = {data["message_base"]}
pub const final_digest_hi = {data["digest_hi"]}
pub const final_digest_low = {data["digest_low"]}
pub const final_verification_key_u = {data["verification_key_u"]}
pub const final_verification_key_v = {data["verification_key_v"]}
pub const final_signature_response = {data["signature_response"]}
pub const final_signature_challenge = {data["signature_challenge"]}
pub const final_schnorr_signature_ascii_hex = #"{schnorr_signature_ascii_hex}"

pub fn final_proof() -> Proof {{
  Proof {{
    piA: #"{proof["piA"]}",
    piB: #"{proof["piB"]}",
    piC: #"{proof["piC"]}",
  }}
}}

pub fn final_public_inputs() -> List<ZKInputType> {{
  [
    Single(final_digest_hi),
    Single(final_digest_low),
    Single(final_verification_key_u),
    Single(final_verification_key_v),
    Single(final_signature_response),
    Single(final_signature_challenge),
  ]
}}

pub fn final_digest_hi_bytes() -> ByteArray {{
  bytearray.from_string(string.from_int(final_digest_hi))
}}

pub fn final_digest_low_bytes() -> ByteArray {{
  bytearray.from_string(string.from_int(final_digest_low))
}}

pub fn final_verification_key_u_bytes() -> ByteArray {{
  bytearray.from_string(string.from_int(final_verification_key_u))
}}

pub fn final_verification_key_v_bytes() -> ByteArray {{
  bytearray.from_string(string.from_int(final_verification_key_v))
}}

pub fn final_signature_response_bytes() -> ByteArray {{
  bytearray.from_string(string.from_int(final_signature_response))
}}

pub fn final_signature_challenge_bytes() -> ByteArray {{
  bytearray.from_string(string.from_int(final_signature_challenge))
}}
"""


def load_jubjub_schnorr_fixture(path: Path = DATA_PATH) -> dict:
    data = read_json(path)
    validate_jubjub_schnorr_fixture(data)
    return data


def write_jubjub_schnorr_fixture(
    output_path: Path = OUTPUT_PATH,
    data_path: Path = DATA_PATH,
) -> None:
    output_path.write_text(render_jubjub_schnorr_fixture(load_jubjub_schnorr_fixture(data_path)))


def check_jubjub_schnorr_fixture(
    output_path: Path = OUTPUT_PATH,
    data_path: Path = DATA_PATH,
) -> None:
    rendered = render_jubjub_schnorr_fixture(load_jubjub_schnorr_fixture(data_path))
    if not output_path.exists():
        raise SystemExit(f"missing generated file: {output_path}")
    if output_path.read_text() != rendered:
        raise SystemExit(
            f"{output_path} is out of date; run jubjub_schnorr_fixture.py to regenerate it"
        )


if __name__ == "__main__":
    write_jubjub_schnorr_fixture()
