[protocol]
name = "zk-bridge"
scope = "eryxcoop"
version = "1.0.0"
description = ""
main = "main.tx3"

[ledger]
family = "cardano"

[[codegen]]
plugin = "rust-client"
output_dir = "./gen/rust-client"
